### ISSUE TITLE
Пропущена буква "t"  в слове "first" в about проекта 

### ISSUE THREAD

**Issue by melonges** [noogen-projects/dapla#3]
<img width="1036" alt="Screen Shot 2022-03-10 at 00 26 47" src="https://user-images.githubusercontent.com/70666395/157539004-b493ab13-718c-45a1-97b0-4ad6f3039c79.png">
<img width="369" alt="Screen Shot 2022-03-10 at 00 26 34" src="https://user-images.githubusercontent.com/70666395/157539010-a10da5b1-a3c7-4a41-9d8f-16073e6a69bf.png">

**Comment by Jerrody** [comment]
> <img alt="Screen Shot 2022-03-10 at 00 26 47" width="1036" src="https://user-images.githubusercontent.com/70666395/157539004-b493ab13-718c-45a1-97b0-4ad6f3039c79.png">
> 
> <img alt="Screen Shot 2022-03-10 at 00 26 34" width="369" src="https://user-images.githubusercontent.com/70666395/157539010-a10da5b1-a3c7-4a41-9d8f-16073e6a69bf.png">

Чел, ты...

**Comment by XX** [comment]
@mellonges Fixed, thanks!
